name: Secrets Action Tester

on:
  workflow_dispatch:

jobs:
  Test-secrets-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get secrets from Infisical Store to memory
        uses: bartonmalow/secrets-action@v1
        with:
            client-id: ${{ secrets.DNA_SECRETS_CLIENT_ID }} # Update this to your own Github references
            client-secret: ${{ secrets.DNA_SECRETS_CLIENT_SECRET }} # Update this to your own Github references
            env-slug: "dev"
            project-slug: "${{ secrets.DNA_SECRETS_PROJECT_SLUG }}"
            secret-path: "/builder-bots"
            domain: "https://dnasecrets.bartonmalow.io"
            export-type: "env"
    
      - name: Test secrets
        run: |
            echo "Secrets loaded successfully"
            echo "GITHUB_OWNER: ${{ env.GITHUB_OWNER }}"
            echo "GITHUB_REPO: ${{ env.GITHUB_REPO }}"

      - name: Get secrets from Infisical store to file
        uses: bartonmalow/secrets-action@v1
        with:
            client-id: ${{ secrets.DNA_SECRETS_CLIENT_ID }} # Update this to your own Github references
            client-secret: ${{ secrets.DNA_SECRETS_CLIENT_SECRET }} # Update this to your own Github references
            env-slug: "dev"
            project-slug: "${{ secrets.DNA_SECRETS_PROJECT_SLUG }}"
            secret-path: "/builder-bots"
            domain: "https://dnasecrets.bartonmalow.io"
            export-type: "file"
            file-output-path: "./secrets.env"

      - name: Print secrets from file
        run: |
            echo "Secrets loaded successfully"
            cat ./secrets.env
            
            
