name: Secrets Action Tester

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Get secrets from Infisical
        uses: ./action.yml
        with:
            client-id: ${{ secrets.DNA_SECRETS_CLIENT_ID }} # Update this to your own Github references
            client-secret: ${{ secrets.DNA_SECRETS_CLIENT_SECRET }} # Update this to your own Github references
            env-slug: "dev"
            project-slug: "${{ secrets.DNA_SECRETS_PROJECT_SLUG }}"
            secret-path: "/builder-bots"
            domain: "https://dnasecrets.bartonmalow.io"