name: Secrets Action Tester

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test-secrets-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #### UNCOMMENT THIS TO RUN THE ACTION LOCALLY
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      # - name: Install Dependencies
      #   run: npm install

      # - name: Get secrets from Infisical
      #   uses: ./
      #   with:
      #       client-id: ${{ secrets.DNA_SECRETS_CLIENT_ID }} # Update this to your own Github references
      #       client-secret: ${{ secrets.DNA_SECRETS_CLIENT_SECRET }} # Update this to your own Github references
      #       env-slug: "dev"
      #       project-slug: "${{ secrets.DNA_SECRETS_PROJECT_SLUG }}"
      #       secret-path: "/builder-bots"
      #       domain: "https://dnasecrets.bartonmalow.io"

      - name: Get secrets from Infisical
        uses: bartonmalow/secrets-action@v1
        with:
            client-id: ${{ secrets.DNA_SECRETS_CLIENT_ID }} # Update this to your own Github references
            client-secret: ${{ secrets.DNA_SECRETS_CLIENT_SECRET }} # Update this to your own Github references
            env-slug: "dev"
            project-slug: "${{ secrets.DNA_SECRETS_PROJECT_SLUG }}"
            secret-path: "/builder-bots"
            domain: "https://dnasecrets.bartonmalow.io"
    
      - name: Test secrets
        run: |
            echo "Secrets loaded successfully"
            echo "GITHUB_OWNER: ${{ env.GITHUB_OWNER }}"
            echo "GITHUB_REPO: ${{ env.GITHUB_REPO }}"
